[layers]

domain = []
contracts = []
application = ["domain", "contracts", "engine"]
engine = ["domain", "contracts"]
infrastructure = ["contracts"]
interface = ["application", "contracts"]
app = ["application", "interface", "infrastructure", "engine", "contracts", "domain", "shared"]
